# Generated by Django 3.2.8 on 2021-10-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skills', models.CharField(max_length=56)),
                ('nationality', models.CharField(max_length=56)),
                ('age', models.SmallIntegerField()),
                ('certificate_issuing_country', models.CharField(max_length=56)),
                ('have_passport', models.BooleanField(default=True)),
                ('valid_us_visa', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
